# Author: Altair Bueno
version: '3.1'
services:
  postgres:
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    volumes:
      - ./sql/test-data.sql:/docker-entrypoint-initdb.d/02.sql
      - authserv-postgres-data:/var/lib/postgresql/data

volumes:
  authserv-postgres-data:
