# Server ip address
# hostname = '127.0.0.1'
# Server port
# port = 9100
[jwt]
# Location of the RSA public key used to verify JWT tokens
publickey = '../public.key'
# Algorithm used
# algorithm='RS256'
# Key kind
# kind='RSAPem'
