openapi: '3.0.2'
info:
  title: Axum transform
  version: '0.0.1'
  license:
    name: MIT
servers:
  - url: http://localhost:9100
    description: Development server
security:
  - bearer: []

paths:
  /:
    post:
      summary: Apply some transformation function to the payload contents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transformation:
                  type: string
                  enum:
                    - capitalize
                data:
                  type: string
            example:
              transformation: capitalize
              data: hello world
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                  took:
                    type: number
                    description: Number of miliseconds that this request took
              example:
                data: HELLO WORLD
                took: 10
        '401':
          $ref: "#/components/responses/Unauthorised"

components:
  schemas:
    Error:
      type: object
      properties:
        timestamp:
          type: string
        message:
          type: string
  responses:
    Unauthorised:
      description: Access token is missing or invalid
      content: 
        application/json:
          schema:
            $ref: "#/components/schemas/Error"  
          example:
            timestamp: 2022-07-31T11:47:02Z
            message: Missing authentication header
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
