openapi: 3.0.0
info:
  title: tsdeno
  version: 0.0.1
  description: |
    Sample using Deno and TypeScript
  license:
    name: MIT
servers:
  - url: http://localhost:9200
    description: Development server
paths:
  /dinos:
    get:
      summary: Fetch all dinos
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Dino"
              example:
                - id: 10
                  name: Juanito
                - id: 11
                  name: Pepe
        "401":
          $ref: "#/components/responses/Unauthorised"
    post:
      summary: Create a new dino
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
            example:
              name: Alfonso
      responses:
        "200":
          description: OK
        "401":
          $ref: "#/components/responses/Unauthorised"
security:
  - bearer: []
components:
  schemas:
    Dino:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string
  responses:
    Unauthorised:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
          example:
            "message": "Missing authorization header"
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
