openapi: 3.0.0
info:
  title: tsdeno
  version: 0.0.1
  description: |
    Sample using Deno and TypeScript
servers:
  - url: http://localhost:9200
    description: Development server
paths:
  /dinos:
    get:
      summary: Fetch all dinos
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      nullable: false
                      type: integer
                    name:
                      nullable: false
                      type: string

    post:
      summary: Create a new dino
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  nullable: false
                  type: string
      responses:
        "200":
          description: OK

security:
  - bearer: []
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
