openapi: 3.0.0
info:
  title: Spring Ping
  version: 0.0.1-SNAPSHOT
  description: |
    Provides ping responses for authorised users
  license:
    name: MIT
servers:
  - url: http://localhost:9000
    description: Development server
security:
  - bearer: []
paths:
  /:
    get:
      summary: Responds to authorised users with a predefined message
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                enum: ["Hello from Spring ping!"]
        "401":
          $ref: "#/components/responses/Unauthorised"

    post:
      summary: Responds to authorised users using the same request body
      requestBody:
        required: true
        content:
          application/json:
              schema:
                type: string
              example: "Hello world"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
              example: "Hello world"
        "401":
          $ref: "#/components/responses/Unauthorised"

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    Unauthorised:
      description: "Unauthorised: Access token is missing or invalid"
