openapi: '3.0.2'
info:
  title: Slow api
  version: '0.0.1'
  description: Fast API JWT micro service for managing todos
  license:
    name: MIT
servers:
  - url: http://localhost:9300
    description: Development server
security:
  - bearer: []

paths:
  /:
    get:
      summary: Get all Todos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
              example:
                - id: ccb5fe7d-a1f1-4a7f-822a-972b47e6be97
                  title: Hello world
                  content: Lorem ipsum
        '401':
          $ref: "#/components/responses/Unauthrorised"
    post: 
      summary: Create todo
      requestBody:
        content:
          application/json:
            schema:
              required:
                - title
                - content
              type: object
              properties:
                title: 
                  type: string
                content:
                  type: string
            example:
              title: Hello world
              content: Lorem ipsum
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
              example:
                id: ccb5fe7d-a1f1-4a7f-822a-972b47e6be97
                title: Hello world
                content: Lorem ipsum
        '401':
          $ref: "#/components/responses/Unauthrorised"
  /{id}:
    get:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            format: uuid
            type: string
          example: ccb5fe7d-a1f1-4a7f-822a-972b47e6be97
      summary: Get Todo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Todo"
              example:
                id: ccb5fe7d-a1f1-4a7f-822a-972b47e6be97
                title: Hello world
                content: Lorem ipsum                  
        '401':
          $ref: "#/components/responses/Unauthrorised"
    post:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            format: uuid
            type: string
          example: ccb5fe7d-a1f1-4a7f-822a-972b47e6be97
      summary: Update todo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title: 
                  type: string
                  nullable: true
                content:
                  type: string
                  nullable: true
            example:
              title: Change the title
      responses:
        '200':
          description: OK
        '401':
          $ref: "#/components/responses/Unauthrorised"
    delete:
      parameters:
        - in: path
          required: true
          name: id
          schema:
            format: uuid
            type: string
          example: ccb5fe7d-a1f1-4a7f-822a-972b47e6be97
      summary: Delete todo
      responses:
        '200':
          description: OK
        '401':
          $ref: "#/components/responses/Unauthrorised"

components:
  responses:
    Unauthrorised:
      description: Unauthorised
  schemas:
    Todo:
      type: object
      required:
        - id
        - title
        - content
      properties:
        id: 
          nullable: false
          type: string
          format: uuid
        title: 
          nullable: false
          type: string
        content: 
          nullable: false
          type: string
      
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
